### ISSUE TITLE
Reuse of secure channel for multiple commands?

### ISSUE THREAD

**Issue by arunsworld** [tom-code/gomat#1]
Hi,

Thanks for putting this library together.

Have noticed that the SigmaExchange appears to take 1.5 seconds for the device I'm using - mainly spent waiting on UDP response.

Is it possible to re-use the secure channel so that the overhead of the SigmaExchange can be paid once?

Calling Send on it multiple times doesn't appear to work at the moment.

Thanks.

**Comment by tom-code** [comment]
hm, it is hard to tell what is wrong. I just tried against chip-lighting-app software device demo and multiple requests over one channel seems to work just fine.
I modified "on" demo command to send on then off. Device receives both commands and I receive both answers.
like this:
```
to_send := gomat.EncodeIMInvokeRequest(1, symbols.CLUSTER_ID_OnOff, symbols.COMMAND_ID_OnOff_On, []byte{}, false, uint16(rand.Intn(0xffff)))
channel.Send(to_send)

resp, err := channel.Receive()
if err != nil {
  panic(err)
}
status, err := resp.Tlv.GetIntRec([]int{1, 0, 1, 1, 0})
if err != nil {
  panic(err)
}
fmt.Printf("result status: %d\n", status)


to_send = gomat.EncodeIMInvokeRequest(1, symbols.CLUSTER_ID_OnOff, symbols.COMMAND_ID_OnOff_Off, []byte{}, false, uint16(rand.Intn(0xffff)))
channel.Send(to_send)

resp, err = channel.Receive()
if err != nil {
  panic(err)
}
status, err = resp.Tlv.GetIntRec([]int{1, 0, 1, 1, 0})
if err != nil {
  panic(err)
}
fmt.Printf("result status: %d\n", status)
```
If device is very slow, did you try to wait a little before sending next command? After response is received library sends ack. Maybe device is not able to handle new command too early after ack.

**Comment by arunsworld** [comment]
Thanks for your quick response. Knowing that it works for you helped me figure out what's going on.

I was doing the switching in a function and passing it gomat.SecureChannel. But the act of Sending mutates the struct (I think the counter?). So the second call had the original copy of gomat.SecureChannel rather than the mutated copy.

Easily fixed by passing a reference instead:

if err := switchLights(&secureChannel, symbols.COMMAND_ID_OnOff_On); err != nil {
	return err
}

if err := switchLights(&secureChannel, symbols.COMMAND_ID_OnOff_Off); err != nil {
	return err
}

Thanks again.

Do you know if the secure channel once created can stay forever given it's UDP or is there a timeout? And also if there is a way to periodically check the channel and refresh it if dead. My idea is to have it ready for use as needed and avoid the latency of creating the secure channel on the hot path.

**Comment by tom-code** [comment]
I am not aware of any explicit timeout on channel/session, but it is probably good idea to be able to verify its state and re-establish if needed.
If you want to verify state of channel/session you can periodically invoke some read request - like to get device uptime - I am not aware of any other method.
Specification says: "Sessions SHALL be discarded and re-established before any Secure Session Message Counter over­ flow or repetition occurs." so your health check requests may actually trigger session discard. (gomat library will currently not do this automatically)

**Comment by arunsworld** [comment]
Thanks a lot. Much appreciated for the prompt responses.
